BEGIN TRANSACTION;

DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
  USERID        INT NOT NULL,
  USERNAME      VARCHAR(32) NOT NULL UNIQUE,
  FIRSTNAME     VARCHAR(32) NOT NULL,
  LASTNAME      VARCHAR(32) NOT NULL,

  PRIMARY KEY (USERID)
);

---------------------------------------------------------------------

INSERT INTO USER (USERID, USERNAME, FIRSTNAME, LASTNAME) VALUES (1, 'dani',  'Dani',     'Dutescu');
INSERT INTO USER (USERID, USERNAME, FIRSTNAME, LASTNAME) VALUES (2, 'delia', 'Ana-Maria',    'Bontescu');
INSERT INTO USER (USERID, USERNAME, FIRSTNAME, LASTNAME) VALUES (3, 'ovi',   'Ovi',     'Bobi');
INSERT INTO USER (USERID, USERNAME, FIRSTNAME, LASTNAME) VALUES (4, 'casi',   'Casi',    'Dr. Holotescu');
INSERT INTO USER (USERID, USERNAME, FIRSTNAME, LASTNAME) VALUES (5, 'radu',   'Radu',    'Mamii');

COMMIT;
