# reference - http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
    port: 8080

spring:
    application:
        name: Spring Boot intro app
    config:
        name: Spring Boot intro app

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update

    security:
        auth:
            usersByUsernameQuery: SELECT userName, password, isActive FROM Users users WHERE users.userName = ?
            authoritiesByUsernameQuery: SELECT users.userName, role.authority FROM Users users LEFT JOIN Role role ON users.id = role.userId WHERE users.userName = ?
